filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/test-app/*.log
    multiline.pattern: '^\d{4}-\d{2}-\d{2} '
    multiline.negate: true
    multiline.match: after
    fields_under_root: true
    fields:
      app_name: test
      env: local
      log_source: spring-logback

processors:
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
