# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082

spring:
  application:
    name: test
  datasource:
    url: jdbc:mysql://localhost:3306/luyian?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  # thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/templates/, classpath:/static/
  jackson:
    time-zone: GMT+8
  clickhouse:
    datasource:
      url: jdbc:clickhouse://59.110.33.127:8123/solarmonitortest
      username: solarmonitor
      password: bzc@2022*qwe123
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver

# 全局配置
my-global:
  file-path: D:/upload

